---
title: "base_graph"
author: "Ashe King"
output: github_document
---

```{r, warning=FALSE, include=FALSE}
# initialize libraries
library(sf)
library(tidyverse)
library(data.table)
library(utils)
library(here)
library(h3jsr)
library(h3r)
library(tmap)
library(dplyr)
library(tidygraph)
library(sfnetworks)
library(igraph)
library(tidyr)
library(ggraph)
library(mapdeck)
library(visNetwork)
library(leaflet)
library(patchwork)

#adjust these values to alter the data included in the graph output
h3_res = 8
min_posts = 20 
max_posts = 600
min_edges = 10 #The lower you go the more noisey the graph output will be 
crs=2263

# Data input
nycDataSept <- fread(here("data/derived_data/user_data/twitter_data_user_origin_2017-09.csv"))
nycDataSept <- nycDataSept %>% filter(is_local == T)
nynta <- read_sf(here("data/raw_data/mapping_data/nynta2020_25d/nynta2020.shp"))
nynta_proj <- st_transform(nynta, crs = crs)
```

# Data transformation
```{r, warning=FALSE}
#Create a h3 cell index on nyc data
h3_nyc_data <- nycDataSept %>% 
  mutate(h3_cell = latLngToCell(lat = lat, lng = lon, resolution = h3_res), home = get_parent(home, res = h3_res)) %>% 
  select(u_id, home, h3_cell)

# filter data to only include NYC data
h3_nyc_data <- h3_nyc_data %>% 
  mutate(geometry = cell_to_point(h3_cell)) %>% 
  st_as_sf() %>%
  st_transform(crs=crs) %>% 
  st_intersection(nynta_proj["BoroName"])

#Save geom
h3_geom <- h3_nyc_data %>% 
  select(h3_cell, geometry)

#Drop Geom for speed
h3_nyc_data <- h3_nyc_data %>% 
  st_drop_geometry()

#selecting user post data where the user posted more than 10 times and less than 200 during study period
h3_nyc_data_slim <- h3_nyc_data %>% 
  group_by(u_id) %>% 
  filter(n() > min_posts && n() < max_posts) %>%
  ungroup() %>% 
  filter(h3_cell != home) # Fitler where posts are made in the User's home region

all_cells <- h3_nyc_data_slim %>% 
  pivot_longer(cols = c(home, h3_cell)) %>% 
  select(cell_name = value) %>% 
  distinct(cell_name)

# Making node table
nodes <- all_cells %>%
  mutate(lat = cellToLatLng(cell_name)$lat, lon = cellToLatLng(cell_name)$lng) %>% 
  distinct(cell_name, .keep_all = T) %>% 
  filter(cell_name != "882a1072c7fffff")

# Making edge table (depreciated: Creates transit web for user between their posts)
# edges <- h3_nyc_data_slim %>% 
#   group_by(u_id) %>% 
#   expand(from = h3_cell, to = h3_cell) %>% #create a to/from col using combination of cells grouped by user id
#   ungroup() %>% 
#   select(from, to) %>% # the resulting DF had over 1mil rows with plently of duplicates
#   group_by(from, to) %>% 
#   mutate(count = n()) %>% # creating count by grouping by distinct from/to pairs
#   ungroup() %>% 
#   distinct(.keep_all = T) %>% # getting rid of duplicate rows
#   filter(from != to) %>%  # removing rows where from node == to node
#   mutate(key1 = pmin(to, from), # creating temp key cols to remove flipped duplicate rows
#          key2 = pmax(to, from)) %>%
#   distinct(key1, key2, .keep_all = TRUE) %>%   # keeping only unique key combinations
#   select(-key1, -key2)   # removing the temporary key columns

# Create Edges (Maps travel between user 'home' and other posted locations)
edges <- h3_nyc_data_slim %>% 
  group_by(home, h3_cell) %>% 
  mutate(count = n()) %>% 
  ungroup() %>% 
  distinct(.keep_all = T)%>%  # removing rows where from node == to node
  mutate(key1 = pmin(home, h3_cell), # creating temp key cols to remove flipped duplicate rows
         key2 = pmax(home, h3_cell)) %>%
  distinct(key1, key2, .keep_all = TRUE) %>%   # keeping only unique key combinations
  select(-key1, -key2)

#filter edges to only contain edges with a count greater than n
edges <- edges %>% 
  filter(count >= min_edges) %>% 
  filter(home != "882a1072c7fffff" & h3_cell != "882a1072c7fffff") %>% 
  rename(from = home, to = h3_cell)


# Making Graph
graph <- tbl_graph(nodes = nodes, edges = edges, directed = T)
graph <-  graph %>%
  activate(nodes) %>%
  mutate(degree = centrality_degree(),
         betweenness = centrality_betweenness())
```

# Ploting the graph
```{r}
# Plot graph
basemap <- ggplot(nynta_proj) +
  geom_sf()
vis_1  <- ggraph(graph, x = lon, y = lat, layout = 'manual') +
  geom_edge_link(aes(width = count), alpha = 0.5, color = "lightblue")+
  geom_node_point(aes(size = degree, color = betweenness)) + 
  scale_size(range = c(0.1, 2))+
 # geom_node_text(aes(label = cell_name), size = 3, repel =T) +
  scale_edge_width(range = c(0.1, 2))+
  scale_color_viridis_c() +
  theme_void()

plot(basemap + vis_1)
```
#Solo network graph visualization
```{r}
plot(vis_1)
```





