---
title: "Data exploration"
author: "Ashe King"
date: "2026-02-26"
output: github_document
---

```{r, warning=FALSE, include=FALSE}
# initialize libraries
library(sf)
library(tidyverse)
library(data.table)
library(utils)
library(here)
library(h3jsr)
library(h3r)
library(tmap)
library(dplyr)
library(tidygraph)
library(sfnetworks)
library(igraph)
library(tidyr)
library(ggraph)
library(mapdeck)
h3_res = 8
```

```{r}
# read in data and store in data table
nycDataSept <- fread(here("analysis/data/derived_data/twitter_with_locality.csv"))
nycDataSept <- nycDataSept %>% filter(is_local == T)
```

```{r}
#Cutting off first 100 rows
sub_nyc_data <- slice_head(nycDataSept, n = 10000)
# Extracting useful data and converting it into a simple feature
sf_nyc_data <- sub_nyc_data %>% 
  select(id, u_id, home, lon, lat) %>% 
  st_as_sf(coords = c("lon", "lat"), crs = 4326)
# plotting the frist 100 posts
ggplot() +
  geom_sf(data = sf_nyc_data["u_id"])
```

```{r}
# Setting up basemap
nynta <- read_sf(here("analysis/data/raw_data/nynta2020_25d/nynta2020.shp"))
nynta_proj <- st_transform(nynta, crs = 6347)
#creating a buffer so these is less edges being left out of h3 grid
nynta_buffer <- nynta_proj["BoroName"] %>% 
  st_buffer(dist = 100)
#Creating H3 gridmap
grid_map <-nynta_buffer %>%
  polygon_to_cells(res = h3_res) %>% 
  cell_to_polygon(simple = T)
# ploting h3 map over basemap
tm_shape(nynta_proj["BoroName"])+
  tm_borders()+
  tm_shape(grid_map)+
  tm_polygons(alpha = 0.5)
```

```{r}
#Creating the interaction matrix for the h3 Cells
#get the h3 Cell names
grid_map_index <- nynta_buffer %>% 
  polygon_to_cells(, res = h3_res)
current_index = 0
#unpack it from the weird list the h3 function outputs
keys <- unlist(grid_map_index)
# create a list of length 2 for martix names, using the h3 cell names as indexes for the matrix
key_list <- list(keys, keys)
# Building martix with cell filled with integer 0 ~1400 col & rows
h3_interaction_matrix <- matrix(data = 0, nrow = length(keys), ncol = length(keys), dimnames = key_list)
```

```{r}
#messing around with the september twitter data to population the matrix

#getting list of unique user IDs
user_ids <- nycDataSept$u_id %>% 
  unique()

#Create a h3 cell index on nyc data
h3_nyc_data <- nycDataSept %>% 
  mutate(h3_cell = latLngToCell(lat = lat, lng = lon, resolution = h3_res)) %>% 
  select(u_id, home, h3_cell)

#selecting user post data where the user posted more than 10 times and less than 200 during study period
h3_nyc_data_slim <- h3_nyc_data %>% 
  group_by(u_id) %>% 
  filter(n() > 60 && n() < 200) %>%
  ungroup()

# converting h3 cells to multipolygons
h3_nyc_data_slim %>% 
  group_by(u_id) %>% 
  pull(h3_cell) %>% 
  cells_to_multipolygon()

#creating cell counts data frame
counted_cells <- h3_nyc_data_slim %>% 
  group_by(h3_cell) %>% 
  mutate(count = n()) %>%
  select(h3_cell, count) %>%
  ungroup() %>% 
  distinct(h3_cell, count) %>%
  mutate(geometry = cell_to_polygon(h3_cell)) %>% 
  st_sf()

#plotting post heatmap
#TODO use the local dataset 
tm_shape(nynta["BoroName"])+
  tm_borders()+
  tm_shape(counted_cells)+
  tm_polygons(fill = "count", 
              fill.scale = tm_scale_intervals(n=5, 
                                              style = 'quantile'),
              fill_alpha = .5)
```
```{r}
#finding the number of unique cells that each user posted in throughout the day
cells_visited <- h3_nyc_data_slim %>% 
  group_by(u_id) %>% 
  distinct(h3_cell, .keep_all = T) %>% 
  mutate(n_cells_visted = n()) %>% ungroup()

#Summarizing the stats of the # of unique cells visited
cells_visited %>% 
  distinct(u_id, .keep_all = T) %>% 
  summarize(avg_num_cell_visted = mean(n_cells_visted),
            max = max(n_cells_visted), 
            min = min(n_cells_visted),
            median = median(n_cells_visted))
h3_nyc_data_slim
```

```{r}
# Making node table
nodes <- h3_nyc_data_slim %>% 
  select(cell_name = h3_cell) %>% 
  mutate(lat = cellToLatLng(cell_name)$lat, lon = cellToLatLng(cell_name)$lng) %>% 
  distinct(cell_name, .keep_all = T)

# simple feature nodes
# sf_nodes <- nodes %>%
#   mutate(geometry = st_centroid(cell_to_polygon(cell_name)))

# Making edge table
edges <- h3_nyc_data_slim %>% 
  group_by(u_id) %>% 
  expand(from = h3_cell, to = h3_cell) %>% #create a to/from col using combination of cells grouped by user id
  ungroup() %>% 
  select(from, to) %>% # the resulting DF had over 1mil rows with plently of duplicates
  group_by(from, to) %>% 
  mutate(count = n()) %>% # creating count by grouping by distinct from/to pairs
  ungroup() %>% 
  distinct(.keep_all = T) %>% # getting rid of duplicate rows
  filter(from != to) %>%  # removing rows where from node == to node
  mutate(key1 = pmin(to, from), # creating temp key cols to remove flipped duplicate rows
         key2 = pmax(to, from)) %>%
  distinct(key1, key2, .keep_all = TRUE) %>%   # keeping only unique key combinations
  select(-key1, -key2)   # removing the temporary key columns

#filter edges to only contain edges with a count greater than n
edges <- edges %>% 
  filter(count >= 10)

# simple feature edges
# sf_edges <- edges %>%
#   rowwise() %>%
#   mutate(
#     geometry = st_sfc(
#       st_linestring(
#         rbind(
#           st_coordinates(cell_to_point(from)),
#           st_coordinates(cell_to_point(to))
#         )
#       )
#     )
#   ) %>%
#   st_as_sf()


# Making Graph
graph <- tbl_graph(nodes = nodes, edges = edges, directed = F)
graph <-  graph %>%
  activate(nodes) %>%
  mutate(degree = centrality_degree(),
         betweenness = centrality_betweenness())

graph

```

```{r}
# Plot graph
  ggraph(graph, x = lon, y = lat, layout = 'manual') +
  geom_edge_link(aes(width = count), alpha = 0.5, color = 'lightblue')+
  geom_node_point(aes(size = degree, color = betweenness)) + 
  scale_size(range = c(0.1, 2))+
 # geom_node_text(aes(label = cell_name), size = 3, repel =T) +
  scale_edge_width(range = c(0.1, 2))+
  scale_color_viridis_c() +
  theme_void()
  
```




