---
title: "Classify local vs non-local"
author: "James McQuilkin"
date: "2026-03-24"
output: html_document
---
#Load Packages
```{r}
library(h3jsr)
library(sf)
library(dplyr)
library(readr)
library(here)
library(data.table)
```

#Prepare NYC Boundary
```{r}
#Load Shapefile
# EPSG 2263: NAD83 / New York Long Island
nyc_outline <- read_sf(here("data/raw_data/mapping_data/nynta2020_25d/nynta2020.shp")) %>%
  st_make_valid() %>%
  st_union() %>%
  st_transform(2263)
```

#Load and Filter Twitter Data
```{r}
twitter_path <- here("data/raw_data/twitter_data/twitter_na_2017-09_ny.csv.gz")

# Load and filter for data type we want
df <- read_csv(twitter_path) %>%
  filter(type == "ll")
```
#Spatial Classification (H3 Home Cells)
```{r}
# Convert unique H3 hex codes to points
home_lookup <- df %>%
  distinct(home) %>%
  mutate(geometry = h3jsr::cell_to_point(home)) %>% 
  st_as_sf() %>% 
  st_transform(st_crs(nyc_outline))

# Check if the home point falls within the NYC outline
home_lookup <- home_lookup %>%
  mutate(is_local = as.logical(st_intersects(geometry, nyc_outline, sparse = FALSE))) %>%
  st_drop_geometry()
```

#Merge and Export Results
```{r}
# Merge results and label
df_final <- df %>%
  left_join(home_lookup, by = "home") %>%
  mutate(user_type = if_else(is_local, "local", "non-local"))

# Export
write_csv(df_final, here("data/derived_data/user_data/twitter_data_user_origin_2017-09.csv"))
```

#Data Validation
```{r}
# Summary table of user types
table(df_final$user_type, useNA = "ifany")
```